### ISSUE TITLE
Search engine pulldown list shows names duplicated in Firefox 43

### ISSUE THREAD

**Issue by NickSto** [NickSto/websearchpro#2]
In the drop-down under the search box, each search engine shows up as a left-aligned name and a right-aligned name (with icon), on the same line:

![mgr5dpm3](https://cloud.githubusercontent.com/assets/645773/11933779/e72cdfb6-a7cb-11e5-94b9-6a928310b7a8.png)

**Comment by bege10** [comment]
This is caused by the add-on "CuteButtons" and fixed in the newest version.

**Comment by Qwerty0** [comment]
@bege10 Oh, do you mean [this addon](https://addons.mozilla.org/en-US/firefox/addon/cutebuttons-crystal-svg/?src=search)? I don't have it installed, but I'm still seeing this problem. Have you tried removing it and adding it back to see if the problem is definitely dependent on it?

**Comment by NickSto** [comment]
@bege10 Oh, do you mean [this addon](https://addons.mozilla.org/en-US/firefox/addon/cutebuttons-crystal-svg/?src=search)? I don't have it installed, but I'm still seeing this problem. Have you tried removing it and adding it back to see if the problem is definitely dependent on it?

**Comment by bege10** [comment]
Yes, this add-on in versions previous to the current 0.4.6. Installing 
and uninstalling caused and solved the problem. With v0.4.6 it is fixed. 
Maybe you have another add-on or css-script that changes the browser view.
